###
### auth_generator Configuration File
###

### Your website title (no sensible default)
title: Deník Referendum
### Your website homepage (default: http://localhost:3000)
url: http://www.denikreferendum.cz
### Administrator email (no sensible default)
email: no-reply@denikreferendum.cz

### Default icon for users (default: /images/auth/buddy.png)
default_icon: /images/auth/buddy.png
### Pixel size of the icons (both width and height)
icon_size: 48

### Allow self-registration (default: true; use false to disable)
allow_self_registration: true

### Allow email confirmation to login (default: false; use true to disable)
need_signup_confirmation: false

### Default User domains (e.g.: "MYORG MEMBERS")
default_domains:

### Format of the user name. Choices are:
###  login: login
###  first: firstname
###   last: lastname
###   name: firstname lastname
###   full: firstname lastname <email>
name_format: login

### The crypt method to store user password. (default: SHA1)
### You can use SHA1, MD5 or SHA1moresalt
crypt_method: SHA1

### You can define a theme you'd like to use for the auth_generator
### Available themes are : default, simple
theme: simple
themeadmin: simple

### Do you want to use Gravatar instead of your oww ?
### For more information see http://www.gravatar.com/
### The default icon will still be used if users have no gravatar
gravatar: false
